name: Run tests on pull request

on: pull_request

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v2
      
    - name : Run tests 
      run : python tests_rpg.py
